version: "2"
services:
  cdcservice:
    image: floodplain/cdcservice:0.0.1
    depends_on:
      - "postgres"
    ports:
      - "8081:8080"
  postgres:
    image: floodplain/floodplain-postgres-demo:1.0.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
